name: hec_venv
channels:
  - conda-forge
  - defaults
dependencies:
  - nomkl
  - sortedcontainers
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - ffmpeg
  - ffmpeg-python
  - py-opencv
  - pip
  - pylint
  - sphinx
  - sphinx_rtd_theme